import { Hono } from "hono";
import { aiService } from "../services/AIService";
import { authMiddleware } from "../middleware/auth";
import { AppEnv } from "../app";
import { z } from "zod";
import { SocketService } from "../services/SocketService";
import { Resume } from "../repositories/Resume";

const ai = new Hono<AppEnv>();

ai.use("*", authMiddleware);

const summarySchema = z.object({
  resumeData: z.record(z.string(), z.any()),
  preferredProvider: z.string().optional(),
  model: z.string().optional(),
});

const bulletsSchema = z.object({
  bullets: z.array(z.string()),
  preferredProvider: z.string().optional(),
  model: z.string().optional(),
});

ai.post("/generate-summary", async (c) => {
  const body = await c.req.json();
  const parsed = summarySchema.safeParse(body);
  if (!parsed.success)
    return c.json({ success: false, errors: parsed.error.format() }, 400);

  const response = await aiService.generate(
    {
      systemPrompt:
        "You are a professional resume writer. Generate a concise, high-impact professional summary based on the provided resume data.",
      userPrompt: JSON.stringify(parsed.data.resumeData),
      model: parsed.data.model,
    },
    parsed.data.preferredProvider,
  );

  SocketService.sendNotification(c.var.userId, "notification", {
    title: "Summary Generation Complete",
    message: "Your professional summary has been generated by AI.",
    type: "success",
  });

  return c.json({ success: true, data: response });
});

ai.post("/improve-bullets", async (c) => {
  const body = await c.req.json();
  const parsed = bulletsSchema.safeParse(body);
  if (!parsed.success)
    return c.json({ success: false, errors: parsed.error.format() }, 400);

  const response = await aiService.generate(
    {
      systemPrompt:
        "You are an ATS optimization expert. Improve the following bullet points to be more impact-oriented and keyword-rich.",
      userPrompt: JSON.stringify(parsed.data.bullets),
      model: parsed.data.model,
    },
    parsed.data.preferredProvider,
  );

  SocketService.sendNotification(c.var.userId, "notification", {
    title: "Bullets Optimized",
    message: "AI successfully enhanced your resume bullet points.",
    type: "success",
  });

  return c.json({ success: true, data: response });
});

ai.post("/analyze-jd", async (c) => {
  const { jobDescription, preferredProvider, model } = await c.req.json();

  const response = await aiService.generate(
    {
      systemPrompt: `You are an expert technical recruiter. Analyze the provided Job Description and return a JSON object with:
    - score: (0-100) match score against typical senior resumes.
    - missingKeywords: array of key technical skills/tools missing or highly prioritized.
    - role: the job title or primary focus.
    - suggestions: array of 3-4 actionable improvements for a resume.`,
      userPrompt: jobDescription,
      responseFormat: "json",
      model: model,
    },
    preferredProvider,
  );

  try {
    const data = JSON.parse(response.content);

    SocketService.sendNotification(c.var.userId, "notification", {
      title: "JD Analysis Complete",
      message: `Your resume matched ${data.score || 0}% of the requirements.`,
      type: "info",
    });

    return c.json({ success: true, data });
  } catch (e) {
    return c.json(
      { success: false, message: "AI failed to generate valid JSON analysis" },
      500,
    );
  }
});

ai.post("/tailor-resume", async (c) => {
  const { resumeId, jobDescription, preferredProvider, model } =
    await c.req.json();

  const resume = await Resume.findOne({ _id: resumeId, userId: c.var.userId });
  if (!resume)
    return c.json({ success: false, message: "Resume not found" }, 404);

  const response = await aiService.generate(
    {
      systemPrompt:
        "You are a professional resume writer. Tailor the resume summary to match the provided job description while remaining honest and impactful.",
      userPrompt: `RESUME_CONTENT: ${JSON.stringify(resume.basics)}\n\nJOB_DESCRIPTION: ${jobDescription}`,
      model: model,
    },
    preferredProvider,
  );

  SocketService.sendNotification(c.var.userId, "notification", {
    title: "Resume Tailored",
    message:
      "Your resume has been successfully tailored to the job description.",
    type: "success",
  });

  return c.json({ success: true, data: { tailoredSummary: response.content } });
});

export default ai;
